package com.parking.system.controller;

import com.parking.system.dto.AddSlotRequest;
import com.parking.system.dto.SlotDTO;
import com.parking.system.service.ParkingService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/slots")
@RequiredArgsConstructor
public class SlotController {

    private final ParkingService parkingService;

    // Constructor generated by @RequiredArgsConstructor

    @PostMapping
    public ResponseEntity<SlotDTO> addSlot(@Valid @RequestBody AddSlotRequest request) {
        return ResponseEntity.ok(parkingService.addSlot(request));
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<String> removeSlot(@PathVariable Long id) {
        parkingService.removeSlot(id);
        return ResponseEntity.ok("Slot removed successfully");
    }

    @GetMapping
    public ResponseEntity<List<SlotDTO>> getAllSlots() {
        return ResponseEntity.ok(parkingService.getAllSlots());
    }
}
